-- Run this in your Supabase SQL Editor

-- 1. Create Profiles Table (if not exists)
create table if not exists profiles (
  id uuid references auth.users on delete cascade not null primary key,
  username text,
  avatar_url text,
  updated_at timestamp with time zone
);

-- 2. Create Meal Logs Table
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  meal_type text not null,
  description text,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Create Workout Logs Table
create table if not exists logs_workout (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  exercise text not null,
  duration int not null, -- minutes
  intensity text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Enable RLS
alter table profiles enable row level security;
alter table logs_meal enable row level security;
alter table logs_workout enable row level security;

-- 5. Policies
-- PROFILES
drop policy if exists "Public profiles are viewable by everyone." on profiles;
create policy "Public profiles are viewable by everyone." on profiles for select using ( true );

drop policy if exists "Users can insert their own profile." on profiles;
create policy "Users can insert their own profile." on profiles for insert with check ( auth.uid() = id );

drop policy if exists "Users can update own profile." on profiles;
create policy "Users can update own profile." on profiles for update using ( auth.uid() = id );

-- MEALS
drop policy if exists "Meals are viewable by everyone." on logs_meal;
create policy "Meals are viewable by everyone." on logs_meal for select using ( true );

drop policy if exists "Users can insert their own meals." on logs_meal;
create policy "Users can insert their own meals." on logs_meal for insert with check ( auth.uid() = user_id );

-- WORKOUTS
drop policy if exists "Workouts are viewable by everyone." on logs_workout;
create policy "Workouts are viewable by everyone." on logs_workout for select using ( true );

drop policy if exists "Users can insert their own workouts." on logs_workout;
create policy "Users can insert their own workouts." on logs_workout for insert with check ( auth.uid() = user_id );

-- 6. Trigger for Auto-Profile Creation (Crucial for Google Auth)
-- This function copies data from auth.users to public.profiles
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, username, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger definition
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
