-- WARNING: RUNNING THIS SCRIPT WILL DELETE ALL EXISTING DATA
-- Single Source of Truth for BodyTune Database Schema
-- Architecture: Denormalized (User info stored in logs), No Profiles Table.

-- 1. Drop existing tables (Reset)
drop table if exists logs_meal;
drop table if exists logs_workout;
drop table if exists profiles; 

-- 2. Create Meal Logs Table
create table logs_meal (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  username text,
  user_avatar text,
  meal_type text not null,
  description text,
  image_url text,
  is_public boolean default true,    -- NEW: Visibility
  log_time timestamp with time zone default timezone('utc'::text, now()) not null, -- NEW: Custom time
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Create Workout Logs Table
create table logs_workout (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  username text,
  user_avatar text,
  exercise text not null,
  duration int not null, 
  intensity text,
  is_public boolean default true,    -- NEW: Visibility
  log_time timestamp with time zone default timezone('utc'::text, now()) not null, -- NEW: Custom time
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Enable RLS
alter table logs_meal enable row level security;
alter table logs_workout enable row level security;

-- 5. Policies
-- MEALS
drop policy if exists "Meals are viewable by everyone." on logs_meal;
create policy "Meals are viewable by everyone." on logs_meal for select using ( true ); -- We filter is_public in the query, but RLS allows read. Or should RLS enforce it?
-- For MVP, query filtering is easier. If we want RLS: create policy ... using ( is_public = true or auth.uid() = user_id ); 
-- Let's stick to open RLS for simplicity, app logic handles filtering.

drop policy if exists "Users can insert their own meals." on logs_meal;
create policy "Users can insert their own meals." on logs_meal for insert with check ( auth.uid() = user_id );

-- WORKOUTS
drop policy if exists "Workouts are viewable by everyone." on logs_workout;
create policy "Workouts are viewable by everyone." on logs_workout for select using ( true );

drop policy if exists "Users can insert their own workouts." on logs_workout;
create policy "Users can insert their own workouts." on logs_workout for insert with check ( auth.uid() = user_id );

-- 6. Clean up Triggers
drop trigger if exists on_auth_user_created on auth.users;
drop function if exists public.handle_new_user();
