-- WARNING: RUNNING THIS SCRIPT WILL DELETE ALL EXISTING DATA
-- Single Source of Truth for BodyTune Database Schema
-- Architecture: Denormalized (User info stored in logs), No Profiles Table.

-- 1. Drop existing tables (Reset)
drop table if exists community_comments;
drop table if exists community_likes;
drop table if exists logs_meal;
drop table if exists logs_workout;
drop table if exists profiles; 

-- 2. Create Meal Logs Table
create table logs_meal (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  username text,
  user_avatar text,
  meal_type text not null,
  description text,
  image_url text,
  is_public boolean default true,
  log_time timestamp with time zone default timezone('utc'::text, now()) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Create Workout Logs Table
create table logs_workout (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  username text,
  user_avatar text,
  exercise text not null,
  duration int not null, 
  intensity text,
  is_public boolean default true,
  log_time timestamp with time zone default timezone('utc'::text, now()) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Create Likes Table (Polymorphic-ish)
create table community_likes (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  meal_id bigint references logs_meal on delete cascade,
  workout_id bigint references logs_workout on delete cascade,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  -- Ensure only one target is set
  check (
    (meal_id is not null and workout_id is null) or
    (meal_id is null and workout_id is not null)
  ),
  -- Ensure unique like per user per item
  unique (user_id, meal_id),
  unique (user_id, workout_id)
);

-- 5. Create Comments Table
create table community_comments (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  username text,      -- Denormalized
  user_avatar text,   -- Denormalized
  meal_id bigint references logs_meal on delete cascade,
  workout_id bigint references logs_workout on delete cascade,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  check (
    (meal_id is not null and workout_id is null) or
    (meal_id is null and workout_id is not null)
  )
);

-- 6. Enable RLS
alter table logs_meal enable row level security;
alter table logs_workout enable row level security;
alter table community_likes enable row level security;
alter table community_comments enable row level security;

-- 7. Policies
-- MEALS
drop policy if exists "Meals are viewable by everyone." on logs_meal;
create policy "Meals are viewable by everyone." on logs_meal for select using ( true );
drop policy if exists "Users can insert their own meals." on logs_meal;
create policy "Users can insert their own meals." on logs_meal for insert with check ( auth.uid() = user_id );

-- WORKOUTS
drop policy if exists "Workouts are viewable by everyone." on logs_workout;
create policy "Workouts are viewable by everyone." on logs_workout for select using ( true );
drop policy if exists "Users can insert their own workouts." on logs_workout;
create policy "Users can insert their own workouts." on logs_workout for insert with check ( auth.uid() = user_id );

-- LIKES
drop policy if exists "Likes are viewable by everyone." on community_likes;
create policy "Likes are viewable by everyone." on community_likes for select using ( true );

drop policy if exists "Users can manage their own likes." on community_likes;
create policy "Users can manage their own likes." on community_likes for all using ( auth.uid() = user_id );

-- COMMENTS
drop policy if exists "Comments are viewable by everyone." on community_comments;
create policy "Comments are viewable by everyone." on community_comments for select using ( true );

drop policy if exists "Users can insert their own comments." on community_comments;
create policy "Users can insert their own comments." on community_comments for insert with check ( auth.uid() = user_id );
drop policy if exists "Users can delete their own comments." on community_comments;
create policy "Users can delete their own comments." on community_comments for delete using ( auth.uid() = user_id );

-- 8. Clean up Triggers
drop trigger if exists on_auth_user_created on auth.users;
drop function if exists public.handle_new_user();

-- 9. Create Character State Table (Gamification)
create table character_state (
  user_id uuid references auth.users not null primary key,
  level int default 1 not null,
  exp int default 0 not null,
  hp int default 100 not null,
  fullness int default 100 not null,
  energy int default 100 not null,
  mood text default 'happy', -- happy, neutral, sad, sick
  last_interaction_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 10. Enable RLS for Character State
alter table character_state enable row level security;

-- 11. Policies for Character State
drop policy if exists "Users can view their own character." on character_state;
create policy "Users can view their own character." on character_state for select using ( auth.uid() = user_id );

drop policy if exists "Users can update their own character." on character_state;
create policy "Users can update their own character." on character_state for update using ( auth.uid() = user_id );

drop policy if exists "Users can insert their own character." on character_state;
create policy "Users can insert their own character." on character_state for insert with check ( auth.uid() = user_id );
